services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rate-service
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - rate-network
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - rate-network

  redis:
    image: redis:7-alpine
    container_name: redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - rate-network

volumes:
  redis_data:

networks:
  rate-network:
