export const globalSymbols = {
  coingecko: {
    usd: 'USD',
    bitcoin: 'BTC',
    ethereum: 'ETH',
    litecoin: 'LTC',
    tether: 'USDT',
    tron: 'TRX',
    amber: 'AMB',
    aptos: 'APT',
    arbitrum: 'ARB',
    'bitcoin-cash': 'BCH',
    binancecoin: 'BNB',
    bittorrent: 'BTT',
    dai: 'DAI',
    dash: 'DASH',
    dogecoin: 'DOGE',
    polkadot: 'DOT',
    'ethereum-classic': 'ETC',
    near: 'NEAR',
    'polygon-ecosystem-token': 'POL',
    solana: 'SOL',
    tontoken: 'TON',
    stellar: 'XLM',
    monero: 'XMR',
    ripple: 'XRP',
    zcash: 'ZEC',
    // KZT, //not found
  },
  coinmarketcap: {
    BTC: 'BTC',
    ETH: 'ETH',
    USDT: 'USDT',
    TRX: 'TRX',
    AMB: 'AMB',
    APT: 'APT',
    ARB: 'ARB',
    BCH: 'BCH',
    BNB: 'BNB',
    BTT: 'BTT',
    DAI: 'DAI',
    DASH: 'DASH',
    DOGE: 'DOGE',
    DOT: 'DOT',
    ETC: 'ETC',
    NEAR: 'NEAR',
    POL: 'POL',
    SOL: 'SOL',
    TON: 'TON',
    XLM: 'XLM',
    XMR: 'XMR',
    XRP: 'XRP',
    ZEC: 'ZEC',
  },
  binance: {
    BTCUSDT: 'BTC',
    ETHUSDT: 'ETH',
    // USDTUSDT: 'USDT',
    TRXUSDT: 'TRX',
    AMBUSDT: 'AMB',
    APTUSDT: 'APT',
    ARBUSDT: 'ARB',
    BCHUSDT: 'BCH',
    BNBUSDT: 'BNB',
    BTTUSDT: 'BTT',
    DAIUSDT: 'DAI',
    DASHUSDT: 'DASH',
    DOGEUSDT: 'DOGE',
    DOTUSDT: 'DOT',
    ETCUSDT: 'ETC',
    NEARUSDT: 'NEAR',
    POLUSDT: 'POL',
    SOLUSDT: 'SOL',
    TONUSDT: 'TON',
    XLMUSDT: 'XLM',
    XMRUSDT: 'XMR',
    XRPUSDT: 'XRP',
    ZECUSDT: 'ZEC',
  },
  cryptoCom: {
    'APTUSD-PERP': 'APT',
    'ARBUSD-PERP': 'ARB',
    'BCHUSD-PERP': 'BCH',
    'BTCUSD-PERP': 'BTC',
    'DAIUSD-PERP': 'DAI',
    'DOGEUSD-PERP': 'DOGE',
    'DOTUSD-PERP': 'DOT',
    'ETCUSD-PERP': 'ETC',
    'ETHUSD-PERP': 'ETH',
    'LTCUSD-PERP': 'LTC',
    'NEARUSD-PERP': 'NEAR',
    'POLUSD-PERP': 'POL',
    'SOLUSD-PERP': 'SOL',
    'TONUSD-PERP': 'TON',
    'XLMUSD-PERP': 'XLM',
    'XRPUSD-PERP': 'XRP',
  },
};

export const coingeckoSymbols = Object.keys(globalSymbols.coingecko);
export const coinMarketCapSymbols = Object.keys(globalSymbols.coinmarketcap);
export const binanceSymbols = Object.keys(globalSymbols.binance);
export const cryptoComSymbols = Object.keys(globalSymbols.cryptoCom);

console.log({
  coingeckoSymbols,
  coinMarketCapSymbols,
  binanceSymbols,
  cryptoComSymbols,
});
